[package]
name = "maze_rewrite"
version = "0.1.0"
edition = "2018"


[dependencies]
rand = "0.8.4"
imageproc = "0.22.0"
image = "*"

# These crates are purely for debug or kewl stuff
# Not really needed
num-format = "0.4.0"